<?php

namespace Asiel\AnimalBundle\Repository\StatusType;

/**
 * DeceasedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeceasedRepository extends \Doctrine\ORM\EntityRepository
{
}
