<?php

namespace Asiel\AnimalBundle\Repository\StatusType;

/**
 * FoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoundRepository extends \Doctrine\ORM\EntityRepository
{
}
