# Backend User
backend_employee_index:
    path:     /
    defaults: { _controller: EmployeeBundle:Backend:index }

backend_employee_show:
    path:     /show/{id}
    defaults: { _controller: EmployeeBundle:Backend:show }

backend_employee_create:
    path:     /create
    defaults: { _controller: EmployeeBundle:Backend:create }

backend_employee_edit:
    path:     /edit/{id}
    defaults: { _controller: EmployeeBundle:Backend:edit }

backend_employee_edit_password:
    path:     /{id}/edit/password
    defaults: { _controller: EmployeeBundle:Backend:editPassword }

backend_employee_profile:
    path:     /{id}/profile
    defaults: { _controller: EmployeeBundle:Backend:profile }

# End Backend User
# Backend UserPicture
backend_employee_user_picture_index:
    path:     /{id}/userpicture
    defaults: { _controller: EmployeeBundle:UserPicture:index }

backend_employee_user_picture_create:
    path:     /{id}/userpicture/create
    defaults: { _controller: EmployeeBundle:UserPicture:create }

backend_employee_user_picture_delete:
    path:     /{id}/userpicture/delete
    defaults: { _controller: EmployeeBundle:UserPicture:delete }
    options:
           expose: true
# End Backend UserPicture
# Backend WorkSchedule
backend_employee_workschedule_index:
    path:     /{id}/workschedule
    defaults: { _controller: EmployeeBundle:WorkSchedule:index }

backend_employee_workschedule_edit:
    path:     /{id}/workschedule/edit
    defaults: { _controller: EmployeeBundle:WorkSchedule:edit }
# End Backend WorkSchedule
