services:
      asiel.employeebundle.userformhandler:
        class: Asiel\EmployeeBundle\Service\UserFormHandler
        arguments:
          - '@asiel.backendbundle.baseformhandler'

      asiel.employeebundle.userpictureformhandler:
        class: Asiel\EmployeeBundle\Service\UserPictureFormHandler
        arguments:
          - '@asiel.backendbundle.baseformhandler'

      asiel.employeebundle.workscheduleformhandler:
        class: Asiel\EmployeeBundle\Service\WorkScheduleFormHandler
        arguments:
          - '@asiel.backendbundle.baseformhandler'