backend_bookkeeping_index:
    path:     /
    defaults: { _controller: BookkeepingBundle:Backend:index }

#Action section
backend_bookkeeping_action_searchanimal:
    path:     /action/searchanimal
    defaults: { _controller: BookkeepingBundle:Backend:searchAnimal }

backend_bookkeeping_action_searchanimal_data:
    path:     /action/searchanimaldata
    defaults: { _controller: BookkeepingBundle:Backend:searchAnimalsData }
    options:
           expose: true

backend_bookkeeping_action_select:
    path:     /action/select/animal/{id}
    defaults: { _controller: BookkeepingBundle:Backend:selectAction }

#End Action section