backend_bookkeeping_index:
    path:     /
    defaults: { _controller: BookkeepingBundle:Backend:index }

#Action
backend_bookkeeping_action_searchanimal:
    path:     /action/searchanimal
    defaults: { _controller: BookkeepingBundle:Action:searchAnimal }

backend_bookkeeping_action_searchcustomer:
    path:     /action/searchcustomer
    defaults: { _controller: BookkeepingBundle:Action:searchCustomer }

backend_bookkeeping_action_select:
    path:     /action/select
    defaults: { _controller: BookkeepingBundle:Action:selectAction }

backend_bookkeeping_action_index:
    path:     /action/
    defaults: { _controller: BookkeepingBundle:Action:index }

backend_bookkeeping_action_show:
    path:     /action/show/{actionid}
    defaults: { _controller: BookkeepingBundle:Action:show }
#End Action
#Action Adopted
backend_bookkeeping_action_adopted_start:
    path:     /action/adopted/start
    defaults: { _controller: BookkeepingBundle:AdoptedAction:start }

backend_bookkeeping_action_adopted_finish:
    path:     /action/{actionid}/adopted/finish
    defaults: { _controller: BookkeepingBundle:AdoptedAction:finish }
#End Action Adopted
#Action Abandoned
backend_bookkeeping_action_abandoned_start:
    path:     /action/abandoned/start
    defaults: { _controller: BookkeepingBundle:AbandonedAction:start }

backend_bookkeeping_action_abandoned_finish:
    path:     /action/{actionid}/abandoned/finish
    defaults: { _controller: BookkeepingBundle:AbandonedAction:finish }
#End Action Abandoned

#Transaction
backend_bookkeeping_transaction_searchcustomer:
    path:     /transaction/searchcustomer
    defaults: { _controller: BookkeepingBundle:Transaction:searchCustomer }

backend_bookkeeping_transaction_create:
    path:     /transaction/create/action
    defaults: { _controller: BookkeepingBundle:Transaction:create }
#End transaction