backend_bookkeeping_index:
    path:     /
    defaults: { _controller: BookkeepingBundle:Backend:index }
#Action
backend_bookkeeping_action_searchanimal:
    path:     /action/searchanimal
    defaults: { _controller: BookkeepingBundle:Action:searchAnimal }

backend_bookkeeping_action_searchcustomer:
    path:     /action/searchcustomer
    defaults: { _controller: BookkeepingBundle:Action:searchCustomer }

backend_bookkeeping_action_select:
    path:     /action/select
    defaults: { _controller: BookkeepingBundle:Action:selectAction }

backend_bookkeeping_action_index:
    path:     /action/
    defaults: { _controller: BookkeepingBundle:Action:index }

backend_bookkeeping_action_show:
    path:     /action/show/{actionid}
    defaults: { _controller: BookkeepingBundle:Action:show }
#End Action
#Action Adopted
backend_bookkeeping_action_adopted_start:
    path:     /action/adopted/start
    defaults: { _controller: BookkeepingBundle:AdoptedAction:start }

backend_bookkeeping_action_adopted_finish:
    path:     /action/{actionid}/adopted/finish
    defaults: { _controller: BookkeepingBundle:AdoptedAction:finish }
#End Action Adopted
#Action Abandoned
backend_bookkeeping_action_abandoned_start:
    path:     /action/abandoned/start
    defaults: { _controller: BookkeepingBundle:AbandonedAction:start }

backend_bookkeeping_action_abandoned_finish:
    path:     /action/{actionid}/abandoned/finish
    defaults: { _controller: BookkeepingBundle:AbandonedAction:finish }
#End Action Abandoned
#Action found
backend_bookkeeping_action_found_start:
    path:     /action/found/start
    defaults: { _controller: BookkeepingBundle:FoundAction:start }

backend_bookkeeping_action_found_extra_costs:
    path:     /action/{actionid}/found/extracosts
    defaults: { _controller: BookkeepingBundle:FoundAction:extraCosts }

backend_bookkeeping_action_found_finish:
    path:     /action/{actionid}/found/finish
    defaults: { _controller: BookkeepingBundle:FoundAction:finish }
#End action found
#Transaction
backend_bookkeeping_transaction_searchcustomer:
    path:     /transaction/searchcustomer
    defaults: { _controller: BookkeepingBundle:Transaction:searchCustomer }

backend_bookkeeping_transaction_create:
    path:     /transaction/create/action
    defaults: { _controller: BookkeepingBundle:Transaction:create }

backend_bookkeeping_transaction_show:
    path:     /transaction/show/{transactionid}
    defaults: { _controller: BookkeepingBundle:Transaction:show }

backend_bookkeeping_transaction_pay:
    path:     /transaction/pay/{transactionid}
    defaults: { _controller: BookkeepingBundle:Transaction:pay }

backend_bookkeeping_transaction_print_single_invoice:
    path:     /transaction/print/singleinvoice/{transactionid}
    defaults: { _controller: BookkeepingBundle:Transaction:printSingleInvoice }
#End transaction
# Seized action
backend_bookkeeping_action_seized_start:
    path:     /action/seized/start
    defaults: { _controller: BookkeepingBundle:SeizedAction:start }

backend_bookkeeping_action_seized_finish:
    path:     /action/{actionid}/seized/finish
    defaults: { _controller: BookkeepingBundle:SeizedAction:finish }
#End seized action
# Returned owner action
backend_bookkeeping_action_returnedowner_start:
    path:     /action/returnedowner/start
    defaults: { _controller: BookkeepingBundle:ReturnedOwner:start }

backend_bookkeeping_action_returnedowner_finish:
    path:     /action/{actionid}/returnedowner/finish
    defaults: { _controller: BookkeepingBundle:ReturnedOwner:finish }
#End Returned owner action
# Cash ledger
backend_bookkeeping_cashledger_index:
    path:     /cashledger
    defaults: { _controller: BookkeepingBundle:CashLedger:index }
#end Cash ledger
#Bank ledger
backend_bookkeeping_bankledger_index:
    path:     /bankledger
    defaults: { _controller: BookkeepingBundle:BankLedger:index }
# end Bank Ledger
#Invoice ledger
backend_bookkeeping_invoiceledger_index:
    path:     /invoiceledger
    defaults: { _controller: BookkeepingBundle:InvoiceLedger:index }

backend_bookkeeping_invoiceledger_searchcustomer:
    path:     /invoiceledger/searchcustomer
    defaults: { _controller: BookkeepingBundle:InvoiceLedger:searchCustomer }

backend_bookkeeping_invoiceledger_invoice_per_customer:
    path:     /invoiceledger/invoicepercustomer/customer/{customerid}
    defaults: { _controller: BookkeepingBundle:InvoiceLedger:invoicePerCustomer }
# end Invoice Ledger