services:
    asiel.bookkeepingbundle.adoptedactionformhandler:
      class: Asiel\BookkeepingBundle\Service\AdoptedActionFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'

    asiel.bookkeepingbundle.actionformhandler:
      class: Asiel\BookkeepingBundle\Service\ActionFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'

    asiel.bookkeepingbundle.transactionformhandler:
      class: Asiel\BookkeepingBundle\Service\TransactionFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'