services:
    asiel.bookkeepingbundle.adoptedactionformhandler:
      class: Asiel\BookkeepingBundle\Service\AdoptedActionFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'
        - '@asiel.bookkeepingbundle.totalactioncosts'

    asiel.bookkeepingbundle.actionformhandler:
      class: Asiel\BookkeepingBundle\Service\ActionFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'

    asiel.bookkeepingbundle.transactionformhandler:
      class: Asiel\BookkeepingBundle\Service\TransactionFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'

    asiel.bookkeepingbundle.abandonedactionformhandler:
      class: Asiel\BookkeepingBundle\Service\AbandonedActionFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'
        - '@asiel.bookkeepingbundle.totalactioncosts'

    asiel.bookkeepingbundle.seizedactionformhandler:
      class: Asiel\BookkeepingBundle\Service\SeizedActionFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'

    asiel.bookkeepingbundle.foundactionformhandler:
      class: Asiel\BookkeepingBundle\Service\FoundActionFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'

    asiel.bookkeepingbundle.returnedowneractionformhandler:
      class: Asiel\BookkeepingBundle\Service\ReturnedOwnerActionFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'

    asiel.bookkeepingbundle.totalactioncosts:
      class: Asiel\BookkeepingBundle\Service\TotalActionCosts
      arguments:
        - '@doctrine.orm.entity_manager'
