# Don't remove backend prefix, used by Security ACL

statistics:
    resource: "@StatisticsBundle/Resources/config/routing.yml"
    prefix:   /backend

location:
    resource: "@LocationBundle/Resources/config/routing.yml"
    prefix: /backend/location

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix: /backend

cms:
    resource: "@CMSBundle/Resources/config/routing.yml"

calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix: /backend

employee:
    resource: "@EmployeeBundle/Resources/config/routing.yml"
    prefix: /backend/employee

customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix: /backend

animal:
    resource: "@AnimalBundle/Resources/config/routing.yml"
    prefix: /backend/animal

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

