security:
    encoders:
        Asiel\EmployeeBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: EmployeeBundle:User
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: backend_default_index
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /login

    access_control:
         - { path: ^/backend, roles: ROLE_USER }