<?php

namespace Asiel\EmployeeBundle\Repository;

/**
 * WorkScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
