# Backend Customer
backend_customer_search_on_lastname:
    path:     /customer/searchonlastname/lastname
    defaults: { _controller: CustomerBundle:BackendCustomer:searchOnLastName }
    options:
           expose: true

backend_customer_edit:
    path:     /customer/edit/{id}
    defaults: { _controller: CustomerBundle:BackendCustomer:edit }

backend_customer_index:
    path:     /customer
    defaults: { _controller: CustomerBundle:BackendCustomer:index }

backend_customer_create:
    path:     /customer/create
    defaults: { _controller: CustomerBundle:BackendCustomer:create }

backend_customer_search_data:
    path:     /customer/searchdata
    defaults: { _controller: CustomerBundle:BackendCustomer:searchCustomersData }
    options:
           expose: true
# End Backend Customer