# Backend Customer
backend_customer_search_on_lastname:
    path:     /backend/customer/searchonlastname/lastname
    defaults: { _controller: CustomerBundle:BackendCustomer:searchOnLastName }
    options:
           expose: true

backend_customer_edit:
    path:     /backend/customer/edit/{id}
    defaults: { _controller: CustomerBundle:BackendCustomer:edit }

# End Backend Customer