# Backend Customer
backend_customer_edit:
    path:     /customer/edit/{id}
    defaults: { _controller: CustomerBundle:BackendCustomer:edit }

backend_customer_index:
    path:     /customer
    defaults: { _controller: CustomerBundle:BackendCustomer:index }

backend_customer_create:
    path:     /customer/create
    defaults: { _controller: CustomerBundle:BackendCustomer:create }

backend_customer_create_private:
    path:     /customer/createprivate
    defaults: { _controller: CustomerBundle:BackendCustomer:createPrivate }

backend_customer_create_business:
    path:     /customer/createbusiness
    defaults: { _controller: CustomerBundle:BackendCustomer:createBusiness }

backend_customer_search_data:
    path:     /customer/searchdata/{requestby}
    defaults: { _controller: CustomerBundle:BackendCustomer:searchCustomersData }
    options:
           expose: true
# End Backend Customer