services:
    asiel.customerbundle.customerformhandler:
      class: Asiel\CustomerBundle\Service\CustomerFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'