<?php

namespace Asiel\CalendarBundle\Repository;

use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * CalendarItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarItemRepository extends EntityRepository
{
    /**
     * Used by Full Calendar
     * @param string $end
     * @param string $start
     * @return array
     */
    public function calendarData($end, $start)
    {
        $end = new DateTime($end);
        $start = new DateTime($start);

        $qb = $this->createQueryBuilder('c');
        $qb->select(
            'c.id, 
            c.title, 
            c.start,
            c.end,
            c.description');
        $qb->where('c.dateDue BETWEEN :start AND :end');
        $qb->setParameter('start', $start->format('Y-m-d'));
        $qb->setParameter('end', $end->format('Y-m-d'));

        return $qb->getQuery()->getResult();
    }



}
