# Login
login:
    path:     /login
    defaults: { _controller: FrontendBundle:Security:login }

logout:
    path: /logout

# End Login
# Frontend Default
frontend_index:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

frontend_animal_search:
    path:     /animal/search
    defaults: { _controller: FrontendBundle:Default:searchAnimals }

frontend_animal_search_data:
    path:     /animal/searchdata
    defaults: { _controller: FrontendBundle:Default:searchAnimalsData }
    options:
          expose : true

frontend_contact:
    path:     /contactus
    defaults: { _controller: FrontendBundle:Default:contact }

frontend_about:
    path:     /aboutus
    defaults: { _controller: FrontendBundle:Default:about }

# End Frontend Default
# Frontend Dog
frontend_dog_index:
    path:     /dogs/{option}
    defaults: { _controller: FrontendBundle:Dog:showDogs }
    options:
           expose: true

frontend_dog_show:
    path:     /dog/show/{id}
    defaults: { _controller: FrontendBundle:Dog:showDog }
    options:
           expose: true

# Frontend Dog End
# Frontend Cat
frontend_cat_index:
    path:     /cats/{option}
    defaults: { _controller: FrontendBundle:Cat:showCats }
    options:
           expose: true

frontend_cat_show:
    path:     /cat/show/{id}
    defaults: { _controller: FrontendBundle:Cat:showCat }
    options:
           expose: true
# Frontend Cat End