services:
    asiel.frontendbundle.defaultformhandler:
      class: Asiel\FrontendBundle\Service\DefaultFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'
        - '@form.factory'
        - '@router'
        - '@mailer'
        - '%contact_email%'
        - '@templating'

    asiel.frontendbundle.catformhandler:
      class: Asiel\FrontendBundle\Service\CatFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'

    asiel.frontendbundle.dogformhandler:
      class: Asiel\FrontendBundle\Service\DogFormHandler
      arguments:
        - '@asiel.backendbundle.baseformhandler'