backend_default_index:
    path:     /home
    defaults: { _controller: BackendBundle:Default:index }

backend_settings_bookkeeping:
    path:     /settings/bookkeeping
    defaults: { _controller: BackendBundle:Settings:bookkeeping }