backend_location_index:
    path:     /
    defaults: { _controller: LocationBundle:Default:index }

backend_location_create:
    path:     /create
    defaults: { _controller: LocationBundle:Default:create }

backend_location_delete:
    path:     /delete/{id}
    defaults: { _controller: LocationBundle:Default:delete }
    options:
           expose: true