backend_location_index:
    path:     /
    defaults: { _controller: LocationBundle:Backend:index }

backend_location_create:
    path:     /create
    defaults: { _controller: LocationBundle:Backend:create }

backend_location_delete:
    path:     /delete/{id}
    defaults: { _controller: LocationBundle:Backend:delete }
    options:
           expose: true