backend_location_index:
    path:     /backend/location
    defaults: { _controller: LocationBundle:Default:index }

backend_location_create:
    path:     /backend/location/create
    defaults: { _controller: LocationBundle:Default:create }

backend_location_delete:
    path:     /backend/location/delete/{id}
    defaults: { _controller: LocationBundle:Default:delete }
    options:
           expose: true