<?php

namespace Asiel\BackendBundle\Repository;

/**
 * BookkeepingSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookkeepingSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
