<?php

namespace Asiel\BackendBundle\Repository;

/**
 * FrontendSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontendSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
