<?php

namespace Asiel\CustomerBundle\Repository;

/**
 * BusinessCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
