<?php

namespace Asiel\CustomerBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    /**
     * Used to search customers on index page.
     * @param array $search
     * @param int $limit
     * @return mixed
     */
    public function findCustomers(array $search, int $limit = 10)
    {
        $searchOn   = $search['searchon'];
        $query      = $search['query'];

        $qb = $this->createQueryBuilder('c');
        $qb->where('c.'.$searchOn.' LIKE :query');
        $qb->setParameter('query', '%'.$query.'%');
        $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
