<?php

namespace Asiel\CustomerBundle\Repository;

/**
 * IDCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IDCardRepository extends \Doctrine\ORM\EntityRepository
{
}
