<?php

namespace Asiel\CustomerBundle\Repository;

/**
 * PrivateCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
