backend_statistics_index:
    path:     /stats
    defaults: { _controller: StatisticsBundle:Backend:index }

# Animal Section
backend_statistics_animal_incoming:
    path:     /stats/animal/incoming
    defaults: { _controller: StatisticsBundle:Backend:animalIncoming }

backend_statistics_animal_incoming_kitten:
    path:     /stats/animal/incomingkitten
    defaults: { _controller: StatisticsBundle:Backend:animalIncomingKitten }

backend_statistics_animal_leaving:
    path:     /stats/animal/leaving
    defaults: { _controller: StatisticsBundle:Backend:animalLeaving }

# End Animal Section
# Customer Section
backend_statistics_customer_actions:
    path:     /stats/customer/actions
    defaults: { _controller: StatisticsBundle:Backend:customerActions }

backend_statistics_customer_actions_show:
    path:     /stats/customer/actions/show/{id}
    defaults: { _controller: StatisticsBundle:Backend:customerActionsShow }
# End Customer Section