services:
    asiel.statisticsbundle.backendformhandler:
      class: Asiel\StatisticsBundle\Service\BackendFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'