# Backend Animal
backend_animal_index:
    path:     /
    defaults: { _controller: AnimalBundle:Backend:index }

backend_animal_search_data:
    path:     /searchdata/{requestby}
    defaults: { _controller: AnimalBundle:Backend:searchAnimalsData }
    options:
           expose: true

backend_animal_create:
    path:     /create
    defaults: { _controller: AnimalBundle:Backend:create }

backend_animal_register:
    path:     /register/{type}
    defaults: { _controller: AnimalBundle:Backend:register }

backend_animal_find_on_chipnumber:
    path:     /findonchipnumber/{chipnumber}
    defaults: { _controller: AnimalBundle:Backend:findOnChipnumber }
    options:
           expose: true

backend_animal_show:
    path:     /show/{id}
    defaults: { _controller: AnimalBundle:Backend:show }
    options:
           expose: true

backend_animal_edit:
    path:     /edit/{id}
    defaults: { _controller: AnimalBundle:Backend:edit }
# End Backend Animal
# Backend Incident
backend_animal_incident_index:
    path:     /{id}/incident
    defaults: { _controller: AnimalBundle:BackendIncident:index }

backend_animal_incident_create:
    path:     /{id}/incident/create
    defaults: { _controller: AnimalBundle:BackendIncident:create }

backend_animal_incident_show:
    path:     /incident/show/{incidentid}
    defaults: { _controller: AnimalBundle:BackendIncident:show }
    options:
           expose: true

backend_animal_incident_delete:
    path:     /incident/delete/{id}
    defaults: { _controller: AnimalBundle:BackendIncident:delete }
    options:
           expose: true

# End Backend Incident
# Backend Medical
backend_animal_medical_index:
    path:     /{id}/medical
    defaults: { _controller: AnimalBundle:BackendMedical:index }

backend_animal_medical_create:
    path:     /{id}/medical/create
    defaults: { _controller: AnimalBundle:BackendMedical:create }

backend_animal_medical_show:
    path:     /medical/show/{medicalid}
    defaults: { _controller: AnimalBundle:BackendMedical:show }
    options:
           expose: true

backend_animal_medical_delete:
    path:     /medical/delete/{id}
    defaults: { _controller: AnimalBundle:BackendMedical:delete }
    options:
           expose: true

# End Backend Medical
# Backend Status
backend_animal_status_index:
    path:     /{id}/status
    defaults: { _controller: AnimalBundle:BackendStatus:index }

backend_animal_status_create:
    path:     /{id}/status/create
    defaults: { _controller: AnimalBundle:BackendStatus:create }

backend_animal_status_create_type:
    path:     /{id}/status/createtype/{type}
    defaults: { _controller: AnimalBundle:BackendStatus:createType }

backend_animal_status_show:
    path:     /status/show/{statusid}
    defaults: { _controller: AnimalBundle:BackendStatus:show }
    options:
           expose: true

backend_animal_status_delete:
    path:     /status/delete/{statusid}
    defaults: { _controller: AnimalBundle:BackendStatus:delete }
    options:
           expose: true
# End Backend Status
# Backend Picture
backend_animal_picture_index:
    path:     /{id}/picture
    defaults: { _controller: AnimalBundle:BackendPicture:index }

backend_animal_picture_create:
    path:     /{id}/picture/create
    defaults: { _controller: AnimalBundle:BackendPicture:create }

backend_animal_picture_show:
    path:     /picture/show/{pictureid}
    defaults: { _controller: AnimalBundle:BackendPicture:show }
    options:
           expose: true

backend_animal_picture_delete:
    path:     /picture/delete/{id}
    defaults: { _controller: AnimalBundle:BackendPicture:delete }
    options:
           expose: true
# End Backend Picture
# Backend Facebook
backend_animal_facebook_index:
    path:     /{id}/facebook/index
    defaults: { _controller: AnimalBundle:BackendFacebook:index }

backend_animal_facebook_post:
    path:     /facebook/post/{id}
    defaults: { _controller: AnimalBundle:BackendFacebook:post }

# End Backend Facebook
# Backend Task
backend_animal_task_index:
    path:     /{id}/task
    defaults: { _controller: AnimalBundle:BackendTask:index }

backend_animal_task_create:
    path:     /{id}/task/create
    defaults: { _controller: AnimalBundle:BackendTask:create }

backend_animal_task_edit:
    path:     /{id}/task/edit/{taskid}
    defaults: { _controller: AnimalBundle:BackendTask:edit }
    options:
           expose: true

backend_animal_task_delete:
    path:     /task/delete/{id}
    defaults: { _controller: AnimalBundle:BackendTask:delete }
    options:
           expose: true
# End Backend Task