services:
    # Services
    asiel.animalbundle.animalformhandler:
      class: Asiel\AnimalBundle\Service\AnimalFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'

    asiel.animalbundle.incidentformhandler:
      class: Asiel\AnimalBundle\Service\IncidentFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'

    asiel.animalbundle.medicalformhandler:
      class: Asiel\AnimalBundle\Service\MedicalFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'

    asiel.animalbundle.statusformhandler:
      class: Asiel\AnimalBundle\Service\StatusFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'