services:
    # Services
    asiel.animalbundle.formhandler:
      class: Asiel\AnimalBundle\Service\FormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'