services:
    # Services
    asiel.animalbundle.animalformhandler:
      class: Asiel\AnimalBundle\Service\AnimalFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'

    asiel.animalbundle.incidentformhandler:
      class: Asiel\AnimalBundle\Service\IncidentFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'

    asiel.animalbundle.medicalformhandler:
      class: Asiel\AnimalBundle\Service\MedicalFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'

    asiel.animalbundle.statusformhandler:
      class: Asiel\AnimalBundle\Service\StatusFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'

    asiel.animalbundle.pictureformhandler:
      class: Asiel\AnimalBundle\Service\PictureFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'

    asiel.animalbundle.facebookformhandler:
      class: Asiel\AnimalBundle\Service\FacebookFormHandler
      arguments:
        - '%facebook_app_id%'
        - '%facebook_app_secret%'
        - '@doctrine.orm.entity_manager'
        - '@router'
        - '@request_stack'
        - '@event_dispatcher'

    asiel.animalbundle.taskformhandler:
      class: Asiel\AnimalBundle\Service\TaskFormHandler
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@event_dispatcher'
        - '@request_stack'
        - '@security.token_storage'